# -*- coding: utf-8 -*-
"""narrative_similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/NishchayMittal/d976960a61b3965642acfc5a679bd490/narrative_similarity.ipynb
"""

!pip install -q torch transformers datasets

test_data = [
    {
        "track_a": "The company announced record profits this quarter.",
        "track_b": "Financial results show strong revenue growth."
    },
    {
        "track_a": "The cat slept on the sofa all day.",
        "track_b": "Stock markets reacted to the interest rate hike."
    }
]

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

MODEL_NAME = "microsoft/deberta-v3-base"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=3
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
model.eval()

def predict(track_a, track_b):
    inputs = tokenizer(
        track_a,
        track_b,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=256
    ).to(device)

    with torch.no_grad():
        logits = model(**inputs).logits

    return torch.argmax(logits, dim=1).item()

predictions = []

for example in test_data:
    label = predict(example["track_a"], example["track_b"])
    predictions.append({"label": label})

predictions

import json

with open("submission.jsonl", "w") as f:
    for p in predictions:
        f.write(json.dumps(p) + "\n")

print("submission.jsonl created")

with open("submission.jsonl") as f:
    for line in f:
        obj = json.loads(line)
        assert "label" in obj
        assert obj["label"] in [0, 1, 2]

print("Submission file format is VALID ✅")